# Generated by Django 5.1.5 on 2025-10-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_docinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='yjs_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DocInvite',
        ),
    ]
